# ==============================================================================
# 03b_automl_backscatter.R
# PURPOSE
#   Train H2O AutoML on size-standardised (450 mm) acoustic backscatter features:
#     - Variant A: per-ping features (one row per ping)
#     - Variant B: 5-ping block mean (to match RNN unit of analysis)
#
# WHAT IT DOES
#   - Ensures transformed backscatter splits exist (runs 02a_check_transformations.R if needed)
#   - Creates per-ping and block-mean datasets
#   - Runs H2O AutoML (10 min budget) on each variant
#   - Saves leaderboards, VALID/TEST predictions, ROC plots, metrics JSON
#   - Saves a MOJO per variant via utils_models.R (tags: bs_orig, bs_blk)
#
# INPUTS (generated by Analysis/02a_check_transformations.R)
#   - outputs/tables/train_backscatter_450.rds
#   - outputs/tables/validate_backscatter_450.rds
#   - outputs/tables/test_backscatter_450.rds
#
# OUTPUTS (timestamped)
#   - outputs/tables/leaderboard_{variant}_{ts}.rds
#   - outputs/tables/preds_{variant}_valid_{ts}.rds
#   - outputs/tables/preds_{variant}_test_{ts}.rds
#   - outputs/tables/automl_metrics_{variant}_{ts}.json
#   - figures/roc_{variant}_{ts}.png
#   - outputs/models/bs_orig/<ts>__<model_id>/... (MOJO, meta.json, etc.)
#   - outputs/models/bs_blk/<ts>__<model_id>/...  (MOJO, meta.json, etc.)
# ==============================================================================

rm(list = ls())
invisible(gc())

suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(lubridate)
  library(glue)
  library(ggplot2)
  library(jsonlite)
})

# ---- make saver available ----------------------------------------------------
# (Requires Analysis/utils_models.R from our standardised saving utility)
source("Analysis/utils_models.R")

# -------- folders --------------------------------------------------------------
dir.create("outputs", showWarnings = FALSE)
dir.create("outputs/tables", showWarnings = FALSE, recursive = TRUE)
dir.create("figures", showWarnings = FALSE, recursive = TRUE)

ts_tag <- format(with_tz(Sys.time(), "Australia/Melbourne"), "%Y%m%d_%H%M%S")
seed   <- 73

# -------- ensure transformed inputs exist -------------------------------------
builder <- here("Analysis","02a_check_transformations.R")
paths <- list(
  train    = here("outputs","tables","train_backscatter_450.rds"),
  validate = here("outputs","tables","validate_backscatter_450.rds"),
  test     = here("outputs","tables","test_backscatter_450.rds")
)
if (!all(file.exists(unlist(paths)))) {
  message("Backscatter files missing — running: ", builder)
  source(builder, local = TRUE)
  stopifnot(all(file.exists(unlist(paths))))
}

train_bs    <- readRDS(paths$train)
validate_bs <- readRDS(paths$validate)
test_bs     <- readRDS(paths$test)

# Frequency columns F45:F170 etc. (allow dotted numeric names)
freq_cols <- names(train_bs)[stringr::str_detect(names(train_bs), "^F\\d+(?:\\.\\d+)?$")]
stopifnot(length(freq_cols) > 0, all(c("Region","species") %in% names(train_bs)))

# -------- helper: 5-ping blocks + mean across time ----------------------------
mk_blocks5 <- function(df) {
  df |>
    dplyr::group_by(Region) |>
    dplyr::mutate(.grp = rep(seq_len(ceiling(dplyr::n()/5)), each = 5, length.out = dplyr::n())) |>
    dplyr::ungroup() |>
    dplyr::group_by(Region, .grp, species) |>
    dplyr::filter(dplyr::n() == 5) |>
    dplyr::summarise(dplyr::across(dplyr::all_of(freq_cols), mean), .groups = "drop")
}

train_blk <- mk_blocks5(train_bs)
valid_blk <- mk_blocks5(validate_bs)
test_blk  <- mk_blocks5(test_bs)

# -------- Variant A: PER-PING -------------------------------------------------
variant_perping <- list(
  name  = "original",   # keeps compatibility with your viewers
  train = train_bs    |> dplyr::select(dplyr::all_of(freq_cols), species),
  valid = validate_bs |> dplyr::select(dplyr::all_of(freq_cols), species),
  test  = test_bs     |> dplyr::select(dplyr::all_of(freq_cols), species)
)

# -------- Variant B: 5-PING BLOCK MEAN ---------------------------------------
variant_blockmean <- list(
  name  = "original_blocks",
  train = train_blk |> dplyr::select(dplyr::all_of(freq_cols), species),
  valid = valid_blk |> dplyr::select(dplyr::all_of(freq_cols), species),
  test  = test_blk  |> dplyr::select(dplyr::all_of(freq_cols), species)
)

variants <- list(variant_perping, variant_blockmean)

# -------- H2O setup -----------------------------------------------------------
if (!requireNamespace("h2o", quietly = TRUE)) install.packages("h2o")
library(h2o)
h2o.init(nthreads = -1)

run_automl <- function(v) {
  message("\n=== AutoML variant: ", v$name, " ===")
  
  # to H2O frames
  hex_train <- as.h2o(v$train)
  hex_valid <- as.h2o(v$valid)
  hex_test  <- as.h2o(v$test)
  
  y <- "species"
  x <- setdiff(names(v$train), y)
  
  # factors
  hex_train[[y]] <- as.factor(hex_train[[y]])
  hex_valid[[y]] <- as.factor(hex_valid[[y]])
  hex_test[[y]]  <- as.factor(hex_test[[y]])
  
  aml <- h2o.automl(
    x = x, y = y,
    training_frame    = hex_train,
    validation_frame  = hex_valid,
    leaderboard_frame = hex_test,
    max_runtime_secs  = 600,   # ~10 minutes
    nfolds            = 0,
    balance_classes   = TRUE,
    sort_metric       = "AUC",
    seed              = seed
  )
  
  lb   <- aml@leaderboard
  best <- aml@leader
  aucv <- suppressWarnings(tryCatch(h2o.auc(h2o.performance(best, hex_valid)), error = function(e) NA_real_))
  message("Leader: ", best@algorithm, " | AUC(valid): ", round(aucv, 3))
  
  # predictions on VALID & TEST
  pv <- h2o.predict(best, hex_valid) |> as.data.frame()
  pt <- h2o.predict(best, hex_test)  |> as.data.frame()
  
  # Bind truth for viewers
  pv <- dplyr::bind_cols(species = as.character(v$valid$species), pv)
  pt <- dplyr::bind_cols(species = as.character(v$test$species),  pt)
  
  # choose probability column for SMB
  prob_col <- if ("SMB" %in% names(pt)) {
    "SMB"
  } else if ("p1" %in% names(pt)) {
    "p1"
  } else {
    setdiff(names(pt)[grepl("^(p\\d+|LT|SMB)$", names(pt))], c("predict","species"))[1]
  }
  stopifnot(!is.na(prob_col), prob_col %in% names(pt))
  
  # simple ROC (TEST)
  roc_df <- {
    truth <- as.integer(pt$species == "SMB")
    score <- pt[[prob_col]]
    o <- order(score, decreasing = TRUE)
    tp <- cumsum(truth[o]); fp <- cumsum(1 - truth[o])
    tpr <- tp / sum(truth); fpr <- fp / sum(1 - truth)
    tibble(fpr = c(0, fpr), tpr = c(0, tpr))
  }
  
  fig_path <- here("figures", glue("roc_{v$name}_{ts_tag}.png"))
  p <- ggplot(roc_df, aes(fpr, tpr)) +
    geom_abline(slope = 1, intercept = 0, colour = "grey60") +
    geom_path() + coord_equal() +
    labs(title = glue("AutoML ROC ({v$name}) — SMB positive"),
         x = "False positive rate", y = "True positive rate") +
    theme_classic()
  ggsave(fig_path, p, width = 6.5, height = 5, dpi = 160)
  
  # save artifacts (tables)
  lb_df   <- as.data.frame(lb)
  lb_path <- here("outputs","tables", glue("leaderboard_{v$name}_{ts_tag}.rds"))
  pv_path <- here("outputs","tables", glue("preds_{v$name}_valid_{ts_tag}.rds"))
  pt_path <- here("outputs","tables", glue("preds_{v$name}_test_{ts_tag}.rds"))
  readr::write_rds(as_tibble(lb_df), lb_path)
  readr::write_rds(as_tibble(pv),    pv_path)
  readr::write_rds(as_tibble(pt),    pt_path)
  
  # small metrics JSON
  metrics <- list(
    variant   = v$name,
    n_train   = nrow(v$train),
    n_valid   = nrow(v$valid),
    n_test    = nrow(v$test),
    roc_png   = fig_path,
    auc_valid = unname(aucv)
  )
  readr::write_file(jsonlite::toJSON(metrics, pretty = TRUE, auto_unbox = TRUE),
                    here("outputs","tables", glue("automl_metrics_{v$name}_{ts_tag}.json")))
  
  # ---- save MOJO for this variant (short tags to avoid Windows path length) ---
  lb_full <- h2o.get_leaderboard(aml, extra_columns = "ALL")
  vtag <- switch(v$name,
                 "original"        = "bs_orig",
                 "original_blocks" = "bs_blk",
                 paste0("bs_", v$name))
  save_h2o_artifacts(
    model       = best,
    tag         = vtag,
    leaderboard = lb_full,
    train       = hex_train,
    save_binary = TRUE
  )
  
  invisible(list(
    name = v$name, auc_valid = unname(aucv),
    leaderboard = lb_path, preds_valid = pv_path, preds_test = pt_path, roc = fig_path
  ))
}

# -------- run both variants ---------------------------------------------------
results <- lapply(variants, run_automl)
message("\nAutoML runs complete. Tables/figures saved, and MOJOs written under outputs/models/bs_*.\n")

# (No global saver here — each variant saves its own MOJO)
